#!/usr/bin/env bash

#
# node-red-contrib-google-smarthome
# Copyright (C) 2024 Claudio Chimera and others.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

. ./data
. ./code

NODE_ID=$1
shift
CMD_=$1

CMD="${CMD_%%_*}"

CMD_FILE=cmd/$CMD_.txt

if [ ! -f $CMD_FILE ] ; then
    echo "Command $CMD_ unknownn"
    exit 1
fi
shift

PARAMS=$(cat $CMD_FILE)
PARAMS=${PARAMS//$'\n'/}
RID=$(date +%s%N)

i=0
for p in "$@" ; do
    ((i++))
    PARAMS=$(echo "$PARAMS" | sed "s/PARAM$i/$p/")
done

SH_REQUEST="{\"inputs\":[{\"context\":{\"locale_country\":\"US\",\"locale_language\":\"en\"},\"intent\":\"action.devices.EXECUTE\",\"payload\":{\"commands\":[{\"devices\":[{\"id\":\"$NODE_ID\"}],\"execution\":[{\"command\":\"action.devices.commands.$CMD\",\"params\":$PARAMS}]}]}}],\"requestId\":\"$RID\"}"

echo "$SH_REQUEST" > request.json

curl -s \
        -H "authorization: Bearer $ACCESS_TOKEN" \
        -H "Content-Type: application/json;charset=UTF-8" \
        --data "$SH_REQUEST" \
        $BASE_URL/smarthome
echo ""
